version: '2.1'
services:
  PostgreSQL:
    restart: always
    image: nikitph/docker-postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  scraper:
    build: .
    depends_on:
      PostgreSQL:
        condition: service_healthy
    command: [ "python3", "./cyclonescrape/datacheck.py && ./cycloneprocess.py"]