version: '2.1'
services:
  db:
    restart: always
    image: nikitph/portcastdbimage:latest
    ports:
      - "5432:5432"
    environment:
      - DEBUG = false
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  scraper:
    build: .
    links:
      - db
    environment:
      - DB_HOST = db
      - BAR = FOO
    depends_on:
      db:
        condition: service_healthy
    command: [sh, -c, "cd ./cyclonescrape && scrapy crawl cyclone && sleep infinity"]